# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_processor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_processor.proto\x12\rfileprocessor\"\x1a\n\x07PdfFile\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\"\"\n\x0fSummaryResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x0eSearchResponse\x12\x11\n\tdocuments\x18\x01 \x03(\t\"$\n\x14SummarizeTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t2\x81\x02\n\rFileProcessor\x12\x46\n\nProcessPdf\x12\x16.fileprocessor.PdfFile\x1a\x1e.fileprocessor.SummaryResponse\"\x00\x12P\n\x0fSearchDocuments\x12\x1c.fileprocessor.SearchRequest\x1a\x1d.fileprocessor.SearchResponse\"\x00\x12V\n\rSummarizeText\x12#.fileprocessor.SummarizeTextRequest\x1a\x1e.fileprocessor.SummaryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_processor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PDFFILE']._serialized_start=39
  _globals['_PDFFILE']._serialized_end=65
  _globals['_SUMMARYRESPONSE']._serialized_start=67
  _globals['_SUMMARYRESPONSE']._serialized_end=101
  _globals['_SEARCHREQUEST']._serialized_start=103
  _globals['_SEARCHREQUEST']._serialized_end=133
  _globals['_SEARCHRESPONSE']._serialized_start=135
  _globals['_SEARCHRESPONSE']._serialized_end=170
  _globals['_SUMMARIZETEXTREQUEST']._serialized_start=172
  _globals['_SUMMARIZETEXTREQUEST']._serialized_end=208
  _globals['_FILEPROCESSOR']._serialized_start=211
  _globals['_FILEPROCESSOR']._serialized_end=468
# @@protoc_insertion_point(module_scope)
