# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import file_processor_pb2 as file__processor__pb2


class FileProcessorStub(object):
    """The file processing service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessPdf = channel.unary_unary(
                '/fileprocessor.FileProcessor/ProcessPdf',
                request_serializer=file__processor__pb2.PdfFile.SerializeToString,
                response_deserializer=file__processor__pb2.SummaryResponse.FromString,
                )
        self.SearchDocuments = channel.unary_unary(
                '/fileprocessor.FileProcessor/SearchDocuments',
                request_serializer=file__processor__pb2.SearchRequest.SerializeToString,
                response_deserializer=file__processor__pb2.SearchResponse.FromString,
                )
        self.SummarizeText = channel.unary_unary(
                '/fileprocessor.FileProcessor/SummarizeText',
                request_serializer=file__processor__pb2.SummarizeTextRequest.SerializeToString,
                response_deserializer=file__processor__pb2.SummaryResponse.FromString,
                )


class FileProcessorServicer(object):
    """The file processing service definition.
    """

    def ProcessPdf(self, request, context):
        """Sends a PDF file and receives a summary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Searches for documents based on a query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeText(self, request, context):
        """Receives text and returns its summary.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessPdf': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPdf,
                    request_deserializer=file__processor__pb2.PdfFile.FromString,
                    response_serializer=file__processor__pb2.SummaryResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=file__processor__pb2.SearchRequest.FromString,
                    response_serializer=file__processor__pb2.SearchResponse.SerializeToString,
            ),
            'SummarizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeText,
                    request_deserializer=file__processor__pb2.SummarizeTextRequest.FromString,
                    response_serializer=file__processor__pb2.SummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileprocessor.FileProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileProcessor(object):
    """The file processing service definition.
    """

    @staticmethod
    def ProcessPdf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fileprocessor.FileProcessor/ProcessPdf',
            file__processor__pb2.PdfFile.SerializeToString,
            file__processor__pb2.SummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fileprocessor.FileProcessor/SearchDocuments',
            file__processor__pb2.SearchRequest.SerializeToString,
            file__processor__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SummarizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fileprocessor.FileProcessor/SummarizeText',
            file__processor__pb2.SummarizeTextRequest.SerializeToString,
            file__processor__pb2.SummaryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
